version: '3'

services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    container_name: phpipam-www
    restart: unless-stopped
    ports:
      - "${PORT:-4050}:80"
    environment:
      - TZ=${TIME_ZONE}
      - IPAM_DATABASE_HOST=${DATABASE_HOST}
      - IPAM_DATABASE_USER=${DATABASE_USER}
      - IPAM_DATABASE_PASS=${DATABASE_PASS}
      - IPAM_DATABASE_NAME=${DATABASE_NAME}
      - IPAM_DATABASE_PORT=${DATABASE_PORT}
      - IPAM_DATABASE_WEBHOST=${DATABASE_WEBHOST}
      #- IPAM_BASE=${BASE}
    volumes:
      - ./phpipam-logo:/phpipam/css/images/logo
      - ./phpipam-ca:/usr/local/share/ca-certificates:ro
  
  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    container_name: phpipam-cron
    restart: unless-stopped
    environment:
      - TZ=${TIME_ZONE}
      - IPAM_DATABASE_HOST=${DATABASE_HOST}
      - IPAM_DATABASE_USER=${DATABASE_USER}
      - IPAM_DATABASE_PASS=${DATABASE_PASS}
      - IPAM_DATABASE_NAME=${DATABASE_NAME}
      - SCAN_INTERVAL=${INTERVAL}
    volumes:
      - ./phpipam-ca:/usr/local/share/ca-certificates:ro
